apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: dev
  contents:
  - path: ./
    git:
      url: https://github.com/blinkbitcoin/blink.git
      ref: cfb4c39306874bbe566017f7d4f26b441e3f6d1f
    includePaths:
    - dev/**/*
    excludePaths:
    - dev/bin/**/*
    - dev/.gitignore
    newRootPath: dev
- path: ./graphql
  contents:
  - path: schemas/
    git:
      url: https://github.com/blinkbitcoin/blink.git
      ref: cfb4c39306874bbe566017f7d4f26b441e3f6d1f
    includePaths:
    - core/api/src/graphql/public/schema.graphql
    - core/api/src/graphql/admin/schema.graphql
    newRootPath: core/api/src/graphql
  - path: gql/
    git:
      url: https://github.com/blinkbitcoin/blink.git
      ref: cfb4c39306874bbe566017f7d4f26b441e3f6d1f
    includePaths:
    - bats/gql/**/*
    newRootPath: bats/gql
